name: Package
on: workflow_dispatch

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    
    - name: Install vsce  
      run: npm install vsce

    - name: Packaging
      run: vsce package

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./*.vsix
        
